### ISSUE TITLE
转码MP

### ISSUE THREAD

**Issue by 979881765** [liunianhuaguoyanxi/ZWAudioRecordTool#1]
您好，怎么边路音频边转码为MP3呢

**Comment by liunianhuaguoyanxi** [comment]
目前业务逻辑还未涉及该需求，你可以参考看看Apple官方文档看看有无这样的设计：https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/AudioQueueProgrammingGuide/AQRecord/RecordingAudio.html
